# Generated by Django 6.0.1 on 2026-01-16 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_journey_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='is_private',
            field=models.BooleanField(default=False),
        ),
    ]
