# Generated by Django 6.0.1 on 2026-01-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_journey_is_private'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='song',
            field=models.FileField(blank=True, null=True, upload_to='journey_songs/'),
        ),
    ]
